config/routes.rb
Rails.application.routes.draw do
  resources :opportunities do
    collection do
      get 'after_edit'
    end
  end

  resources :companies do
    collection do
      get 'after_edit'
    end
  end

  resources :people do
    collection do
      get 'after_edit'
      get 'by_company/:company_id' => 'people#by_company'
    end
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "people#index"
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :user
  mount_uploader :ava, AvaUploader

  has_many :company_people, :inverse_of => :person
  accepts_nested_attributes_for :company_people, reject_if: :all_blank, allow_destroy: true

  has_many :opportunities
  
  validates :name, presence: true

  broadcasts_to ->(person) { 'people' }, inserts_by: :prepend

  paginates_per 10
  
  scope :ordered, -> { order(id: :desc) }
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  protect_from_forgery except: [:by_company]
  include Responsible
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  def index
    @people = Person.page(params[:page])
  end

  def new
    @person = Person.new
    @framed = true
    @after_cancel = after_edit_people_path
  end

  def create
    @person = Person.new(person_params)
    
    if @person.save
      respond_with_item(people_path, 'Person')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @person.destroy
    
    respond_with_item(people_path, 'Person')
  end

  def update
    if @person.update(person_params)
      respond_for_update(people_path, person_path(@person), 'Person')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def edit
    @framed = respond_for_cancel
    path_to = @framed ? people_path : person_path(@person)
    @after_cancel = path_to
  end

  def by_company
    company_id = params[:company_id]

    result_list = CompanyPerson.joins(:person).where( company_id: company_id ).pluck(:person_id, :name).map { |rec| {id: rec[0], name: rec[1]} }

    respond_to do |format|
      format.js { render json: result_list }
    end
  end

  private

  def set_person
    @person = Person.find(params[:id])
  end

  def person_params
    params.require(:person).permit(:name, :phone, :email, :web, :twitter, :user_id, :about, :ava, company_people_attributes: [:id, :company_id, :role, :_destroy])
  end

end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_edit_entry.html.haml
.border.edit_entry
  = render "form", person: @person

app/views/people/_form.html.haml
= nested_form_for @person do |f|
  - if @person.errors.any?
    #error_explanation
      %h2= "#{pluralize(@person.errors.count, "error")} prohibited this person from being saved:"
      %ul
        - @person.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    Avatar picture:
    = @person.ava if @person.ava?
    = f.file_field :ava, :class=>"form-control ava_loader", :label=>"Avatar"

  .form-group
    = f.label :name
    = f.text_field :name, :class=>'form-control', placeholder: "Person Name"

  .form-group
    = f.label :phone
    = f.text_field :phone, :class=>'form-control', placeholder: "Person Phone"

  .form-group
    = f.label :email
    = f.text_field :email, :class=>'form-control', placeholder: "Person Email"

  .form-group
    = f.label :web
    = f.text_field :web, :class=>'form-control', placeholder: "Person Web"

  .form-group
    = f.label :twitter
    = f.text_field :twitter, :class=>'form-control', placeholder: "Person Twitter"

  .form-group
    = f.label :user
    = f.collection_select :user_id, User.all, :id, :name, {}, {class: "form-control"}

  .form-group
    = f.label :about
    = f.text_area :about, :class=>'form-control', placeholder: "About Person"

    %h4.top_space Companies:
    %div{ 'data-controller' => 'nested-fields' }
      %template{ 'data-nested-fields-target'=>'template' }
        = f.fields_for :company_people, CompanyPerson.new, child_index: 'TEMPLATE_RECORD' do |c|
          .nested-form-wrapper.nested-fields.top_space{ 'data-controller' => 'choice-item' }
            .form-group
              = c.label :company
              = c.collection_select :company_id, Company.order(:name), :id, :name, {:include_blank => false}, 'data-choice-item-target'=>'selected_item', :class=>"select2"

            .form-group
              = c.label :role
              = c.text_field :role, :class=>'form-control'

            = c.hidden_field :_destroy
            .float-end
              = link_to 'Remove company', '#', data: { action: 'click->nested-fields#remove_record' }

      
      = f.fields_for :company_people do |c|
        .nested-form-wrapper.nested-fields.top_space{ 'data-controller' => 'choice-item' }
          .form-group
            = c.label :company
            = c.collection_select :company_id, Company.order(:name), :id, :name, {:include_blank => false}, 'data-choice-item-target'=>'selected_item', :class=>"select2"

          .form-group
            = c.label :role
            = c.text_field :role, :class=>'form-control'

          = c.hidden_field :_destroy
          .float-end
            = link_to '- Remove company', '#', data: { action: 'click->nested-fields#remove_record' }

      %div.top_space{ 'data-nested-fields-target'=>'add_item' }
        = link_to '+ Add company', '#', data: { action: 'click->nested-fields#add_record' }

  .actions.top_space
    = f.submit 'Save', :class=>"btn btn-success"
    - cancel_attr = { :class=>"btn btn-info"}
    - cancel_attr[:data] = { turbo_frame: '_top' } unless @framed

    = link_to 'Cancel', @after_cancel, cancel_attr

app/views/people/_new_menu.html.haml
= turbo_frame_tag Person.new do
  = link_to 'New Person', new_person_path, data: { turbo_frame: Person.new }

app/views/people/_person.html.haml
= turbo_frame_tag person do
  .person.border.entry1
    .row
      .col-md-1
        - ava_pic = person.ava.thumb.url ? person.ava.thumb.url: 'thumb_anonymous.png'
        = image_tag(ava_pic, :class=>"ava_pic", size: "150x150")
      .col-md-11
        %h2.index_show_button
          = link_to person.name, person_path(person), data: { turbo_frame: '_top' }
        %p.about_text
          = person.about

        .row
          .col-md-8
          .col-md-2
            = button_to 'Edit', edit_person_path(person), method: :get, class: 'btn btn-link'
          .col-md-2
            = button_to 'Delete', person_path(person), method: :delete, class: 'btn btn-link', form: { data: { turbo_confirm: "Are you sure you want to delete this?"} }

app/views/people/_short_person.html.haml
- ava_pic = person.ava.middle.url ? person.ava.middle.url : 'middle_anonymous.png'
= link_to(image_tag(ava_pic, :class=>"person_ava_pic"), person, :title=>person.name, :class => "thumb_ava")
%h3
  = link_to person.name, person

app/views/people/after_edit.html.haml
= turbo_frame_tag 'new_person' do
  = render partial: 'new_menu'

app/views/people/create.turbo_stream.erb
<%= turbo_stream.prepend "people", partial: 'people/person', locals: { person: @person } %>
<%= turbo_stream.update Person.new, partial: 'new_menu' %>
<%= render_turbo_stream_flash_message %>

app/views/people/destroy.turbo_stream.erb
<%= turbo_stream.remove @person %>
<%= render_turbo_stream_flash_message %>

app/views/people/edit.html.haml
- if @framed
  = turbo_frame_tag @person do
    = render "edit_entry", person: @person
- else
  = render "edit_entry", person: @person

app/views/people/index.html.haml
= turbo_stream_from 'people'

%h1 People

= turbo_frame_tag "people" do
  - @people.ordered.each do |person|
    = render person

%p{:class=>'clearfix'}
  = paginate @people

- content_for :sidebar do
  .container
    %h4 Add:
    = render partial: '/shared/new_menu'

app/views/people/new.html.haml
= turbo_frame_tag Person.new do
  = render 'form'

app/views/people/show.html.haml
%p#notice= notice

%h1
  = @person.name

%h2 Companies:
- @person.company_people.each do |company_person|
  = render partial: "company_people/short_person_company", locals: {company_person: company_person}

%h2{ style: 'clear:both' } Opportunities:
- @person.opportunities.each do |opportunity|
  = render partial: "opportunities/opportunity", locals: {opportunity: opportunity}

- content_for :sidebar do
  - ava_pic = @person.ava.normal.url ? @person.ava.normal.url: 'thumb_anonymous.png'
  .ava_holder
    = image_tag ava_pic, :class=>"ava_big_pic"
  .border.about_text_frame
    %p{:class=>"show_field"}
      %b About:
      = @person.about
  %p{:class=>"show_field"}
    %b Phone:
    = @person.phone
  %p{:class=>"show_field"}
    %b Email:
    = @person.email
  %p{:class=>"show_field"}
    %b Facebook:
    = @person.facebook
  %p{:class=>"show_field"}
    %b Twitter:
    = @person.twitter
  %p{:class=>"show_field"}
    %b Web:
    = @person.web

  %p{:class=>"show_field"}
    %b Curator:
    = @person.user.name

  = link_to 'Edit', edit_person_path(@person)
  \|
  = link_to 'Back to People list', people_path

app/views/people/update.turbo_stream.erb
<%= turbo_stream.replace @person %>
<%= render_turbo_stream_flash_message %>