config/routes.rb
Rails.application.routes.draw do
  resources :opportunities do
    collection do
      get 'after_edit'
    end
  end

  resources :companies do
    collection do
      get 'after_edit'
    end
  end

  resources :people do
    collection do
      get 'after_edit'
      get 'by_company/:company_id' => 'people#by_company'
    end
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "people#index"
end

app/views/shared/_flash.html.haml
- flash.each do |flash_type, message|
  .flash_message{ 'data-controller' => "removals", 'data-action' => "change->removals#remove" }
    = message

app/views/shared/_menu.html.haml
.navbar.navbar-dark.navbar-expand-lg.bg-primary{role: "navigation"}
  .container-fluid
    %a{class: "navbar-brand", href: "/"}
      JustCRM
    .collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        %li.nav-item
          = link_to "People", people_path, class: "nav-link #{'active' if controller_name == 'people'}"
        %li.nav-item
          = link_to "Companies", companies_path, class: "nav-link #{'active' if controller_name == 'companies'}"
        %li.nav-item
          = link_to "Sales", opportunities_path, class: "nav-link #{'active' if controller_name == 'opportunities'}"

      %ul.navbar-nav.pull-right
        - if user_signed_in?
          %li.nav-item
            = link_to "#{current_user.email}", '', class: "nav-link"
          %li.nav-item
            = link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link"
        - else
          %li.nav-item
            = link_to "Login", new_user_session_path, class: "nav-link"
          %li.nav-item
            = link_to "SignUp", new_user_registration_path, class: "nav-link"

app/views/shared/_new_menu.html.haml
= turbo_frame_tag Person.new do
  = link_to 'New Person', new_person_path, data: { turbo_frame: Person.new }
%br
= turbo_frame_tag Company.new do
  = link_to 'New Company', new_company_path, data: { turbo_frame: Company.new }
%br
= turbo_frame_tag Opportunity.new do
  = link_to 'New Opportunity', new_opportunity_path, data: { turbo_frame: Opportunity.new }