config/routes.rb
Rails.application.routes.draw do
  resources :opportunities do
    collection do
      get 'after_edit'
    end
  end

  resources :companies do
    collection do
      get 'after_edit'
    end
  end

  resources :people do
    collection do
      get 'after_edit'
      get 'by_company/:company_id' => 'people#by_company'
    end
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "people#index"
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user

  has_many :company_people, :inverse_of => :company
  accepts_nested_attributes_for :company_people, reject_if: :all_blank, allow_destroy: true

  has_many :opportunities

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length: { minimum: 3 }

  broadcasts_to ->(company) { 'companies' }, inserts_by: :prepend

  mount_uploader :ava, AvaUploader
  paginates_per 10

  scope :ordered, -> { order(id: :desc) }
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  include Responsible
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  def index
    @companies = Company.page(params[:page])
  end

  def new
    @company = Company.new
    @framed = true
    @after_cancel = after_edit_companies_path
  end

  def create
    @company = Company.new(company_params)
    
    if @company.save
      respond_with_item(companies_path, 'Company')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @company.destroy

    respond_with_item(companies_path, 'Company')
  end

  def update
    if @company.update(company_params)
      respond_for_update(companies_path, company_path(@company), 'Company')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def edit
    @framed = respond_for_cancel
    path_to = @framed ? companies_path : company_path(@company)
    @after_cancel = path_to
  end

  private

  def set_company
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(:name, :phone, :web, :address, :user_id, :about, :ava, company_people_attributes: [:id, :person_id, :role, :_destroy])
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.haml
= turbo_frame_tag company do
  .company.border.entry1
    .row
      .col-md-1
        - ava_pic = company.ava.thumb.url ? company.ava.thumb.url: 'anonym_company.png'
        = image_tag(ava_pic, :class=>"ava_pic", size: "150x150")
      .col-md-11
        %h2.index_show_button
          = link_to company.name, company_path(company), data: { turbo_frame: '_top' }
        %p.about_text
          = company.about

        .row
          .col-md-8
          .col-md-2
            = button_to 'Edit', edit_company_path(company), method: :get, class: 'btn btn-link'
          .col-md-2
            = button_to 'Delete', company_path(company), method: :delete, class: 'btn btn-link', form: { data: { turbo_confirm: "Are you sure you want to delete this?"} }

app/views/companies/_edit_entry.html.haml
.border.edit_entry
  = render "form", company: @company

app/views/companies/_form.html.haml
= nested_form_for @company do |f|
  - if @company.errors.any?
    #error_explanation
      %h2= "#{pluralize(@company.errors.count, "error")} prohibited this company from being saved:"
      %ul
        - @company.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    Avatar picture:
    = @company.ava if @company.ava?
    = f.file_field :ava, :class=>"form-control ava_loader", :label=>"Avatar"

  .form-group
    = f.label :name
    = f.text_field :name, :class=>'form-control', placeholder: "Company Name"

  .form-group
    = f.label :phone
    = f.text_field :phone, :class=>'form-control', placeholder: "Company Phone"

  .form-group
    = f.label :web
    = f.text_field :web, :class=>'form-control', placeholder: "Company Web"

  .form-group
    = f.label :address
    = f.text_area :address, :class=>'form-control', placeholder: "Company Address"

  .form-group
    = f.label :user
    = f.collection_select :user_id, User.all, :id, :name, {}, {class: "form-control"}

  .form-group
    = f.label :about
    = f.text_area :about, :class=>'form-control', placeholder: "About Company"

    %h4.top_space People:
    %div{ 'data-controller' => 'nested-fields' }
      %template{ 'data-nested-fields-target'=>'template' }
        = f.fields_for :company_people, CompanyPerson.new, child_index: 'TEMPLATE_RECORD' do |c|
          .nested-form-wrapper.nested-fields.top_space{ 'data-controller' => 'choice-item' }
            .form-group
              = c.label :person
              = c.collection_select :person_id, Person.order(:name), :id, :name, {:include_blank => false}, 'data-choice-item-target'=>'selected_item', :class=>"select2"

            .form-group
              = c.label :role
              = c.text_field :role, :class=>'form-control'

            = c.hidden_field :_destroy
            .float-end
              = link_to 'Remove person', '#', data: { action: 'click->nested-fields#remove_record' }

      
      = f.fields_for :company_people do |c|
        .nested-form-wrapper.nested-fields.top_space{ 'data-controller' => 'choice-item' }
          .form-group
            = c.label :person
            = c.collection_select :person_id, Person.order(:name), :id, :name, {:include_blank => false}, 'data-choice-item-target'=>'selected_item', :class=>"select2"

          .form-group
            = c.label :role
            = c.text_field :role, :class=>'form-control'

          = c.hidden_field :_destroy
          .float-end
            = link_to '- Remove person', '#', data: { action: 'click->nested-fields#remove_record' }

      %div.top_space{ 'data-nested-fields-target'=>'add_item' }
        = link_to '+ Add person', '#', data: { action: 'click->nested-fields#add_record' }

  .actions.top_space
    = f.submit 'Save', :class=>"btn btn-success"
    - cancel_attr = { :class=>"btn btn-info"}
    - cancel_attr[:data] = { turbo_frame: '_top' } unless @framed
    
    = link_to 'Cancel', @after_cancel, cancel_attr

app/views/companies/_new_menu.html.haml
= turbo_frame_tag Company.new do
  = link_to 'New Company', new_company_path, data: { turbo_frame: Company.new }

app/views/companies/_short_company.html.haml
- ava_pic = company.ava.middle.url ? company.ava.middle.url : 'thumb_anonym_company.png'
= link_to(image_tag(ava_pic, :class=>"company_ava_pic"), company, :title=>company.name, :class => "thumb_ava")
%h3
  = link_to company.name, company

app/views/companies/after_edit.html.haml
= turbo_frame_tag 'new_company' do
  = render partial: 'new_menu'

app/views/companies/create.turbo_stream.erb
<%= turbo_stream.prepend "company", partial: 'companies/company', locals: { company: @company } %>
<%= turbo_stream.update Company.new, partial: 'new_menu' %>
<%= render_turbo_stream_flash_message %>

app/views/companies/destroy.turbo_stream.erb
<%= turbo_stream.remove @company %>
<%= render_turbo_stream_flash_message %>

app/views/companies/edit.html.haml
- if @framed
  = turbo_frame_tag @company do
    = render "edit_entry", company: @company
- else
  = render "edit_entry", company: @company

app/views/companies/index.html.haml
= turbo_stream_from 'companies'

%h1 Companies

= turbo_frame_tag "companies" do
  - @companies.ordered.each do |company|
    = render company

%p{:class=>'clearfix'}
  = paginate @companies

- content_for :sidebar do
  .container
    %h4 Add:
    = render partial: '/shared/new_menu'

app/views/companies/new.html.haml
= turbo_frame_tag Company.new do
  = render 'form'

app/views/companies/show.html.haml
%p#notice= notice

%h1
  = @company.name

%h2 People:
- @company.company_people.each do |company_person|
  = render partial: "company_people/short_company_person", locals: {company_person: company_person}

%h2{ style: 'clear:both' } Opportunities:
- @company.opportunities.each do |opportunity|
  = render partial: "opportunities/opportunity", locals: {opportunity: opportunity}

- content_for :sidebar do
  - ava_pic = @company.ava.normal.url ? @company.ava.normal.url: 'thumb_anonymous.png'
  .ava_holder
    = image_tag ava_pic, :class=>"ava_big_pic"
  .border.about_text_frame
    %p{:class=>"show_field"}
      %b About:
      = @company.about
  %p{:class=>"show_field"}
    %b Phone:
    = @company.phone
  %p{:class=>"show_field"}
    %b Address:
    = @company.address
  %p{:class=>"show_field"}
    %b Web:
    = @company.web

  %p{:class=>"show_field"}
    %b Curator:
    = @company.user.name

  = link_to 'Edit', edit_company_path(@company)
  \|
  = link_to 'Back to Companies list', companies_path

app/views/companies/update.turbo_stream.erb
<%= turbo_stream.replace @company %>
<%= render_turbo_stream_flash_message %>