config/routes.rb
Rails.application.routes.draw do
  resources :opportunities do
    collection do
      get 'after_edit'
    end
  end

  resources :companies do
    collection do
      get 'after_edit'
    end
  end

  resources :people do
    collection do
      get 'after_edit'
      get 'by_company/:company_id' => 'people#by_company'
    end
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "people#index"
end

app/models/opportunity.rb
class Opportunity < ApplicationRecord
  belongs_to :company
  belongs_to :person
  belongs_to :user

  validates :title, presence: true
  validates :title, length: { minimum: 4 }
  validates :company, presence: true

  validate :person_must_match_to_company

  scope :ordered, -> { order(id: :desc) }

  STAGES_LIST = [:awareness, :interest, :decision, :buy]

  STATUS_LIST = [ 
    :open, :finished, :canceled
  ]

  def get_stage
    STAGES_LIST[stage]
  end

  def set_stage(stage_name)
    self.stage = STAGES_LIST.index(stage_name)
  end

  def next_stage
    self.stage += 1 if self.stage < 3
  end

  def prev_stage
    self.stage -= 1 if self.stage > 0
  end

  def is_last_stage?
    self.stage == 3
  end

  def is_first_stage?
    self.stage == 0
  end

  def get_status
    STATUS_LIST[status]
  end

  def set_status(status_name)
    self.status = STATUS_LIST.index(status_name)
  end

  def self.statuses
    STATUS_LIST
  end

  private

  def person_must_match_to_company
    return if !person

    company.company_people.each do |link|
      return if link.person == person
    end
    errors.add(:person, "Person must present the company")
  end

end

app/controllers/opportunities_controller.rb
class OpportunitiesController < ApplicationController
  include Responsible
  before_action :set_opportunity, only: [:show, :edit, :update, :destroy]

  def index
    @opportunities = Opportunity.page(params[:page])
  end

  def new
    @opportunity = Opportunity.new
    @opportunity.start = Date.today
    @opportunity.user = current_user

    @framed = true

    @after_cancel = after_edit_opportunities_path
  end

  def create
    @opportunity = Opportunity.new(opportunity_params)

    if @opportunity.save
      respond_with_item(opportunities_path, 'Opportunity')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @opportunity.destroy
    
    respond_with_item(opportunities_path, 'Opportunity')
  end

  def update
    if @opportunity.update(opportunity_params)
      respond_for_update(opportunities_path, opportunity_path(@opportunity), 'Opportunity')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def edit
    @framed = respond_for_cancel
    path_to = @framed ? opportunities_path : opportunity_path(@opportunity)
    @after_cancel = path_to
  end

  private

  def set_opportunity
    @opportunity = Opportunity.find(params[:id])
  end

  def opportunity_params
    params.require(:opportunity).permit(:title, :start, :finish, :description, :stage, :status, :company_id, :person_id, :amount, :user_id, :stage, :status)
  end
end

app/helpers/opportunities_helper.rb
module OpportunitiesHelper
end

app/views/opportunities/_edit_entry.html.haml
.border.edit_entry
  = render "form", opportunity: @opportunity

app/views/opportunities/_form.html.haml
= nested_form_for @opportunity do |f|
  - if @opportunity.errors.any?
    #error_explanation
      %h2= "#{pluralize(@opportunity.errors.count, "error")} prohibited this person from being saved:"
      %ul
        - @opportunity.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :title
    = f.text_field :title, :class=>'form-control', placeholder: "Title"

  .form-group
    = f.label :start
    = f.text_field :start, type: 'date', :class=>'form-control', placeholder: "Start Date"

  .form-group
    = f.label :finish
    = f.text_field :finish, type: 'date', :class=>'form-control', placeholder: "Finish Date"
  %div{ 'data-controller' => 'people-of-customer' }
    .form-group
      = f.label :company_id
      = f.collection_select :company_id, Company.all, :id, :name, {}, data: { action: 'change->people-of-customer#set_people' }, class: "form-control"

    .form-group
      = f.label :person_id
      = f.collection_select :person_id, Person.all, :id, :name, {:include_blank => false}, 'data-people-of-customer-target'=>'person_list', class: "form-control"

  .form-group
    = f.label :amount
    = f.text_field :amount, :class=>'form-control', placeholder: "Amount"

  .form-group
    = f.label :stage
    = f.collection_select :stage, select_data_from_array(Opportunity::STAGES_LIST), :value, :caption, {}, {class: 'form-control'}

  .form-group
    = f.label :status
    = f.collection_select :status, select_data_from_array(Opportunity::STATUS_LIST), :value, :caption, {}, {class: 'form-control'}

  .form-group
    = f.label :user
    = f.collection_select :user_id, User.all, :id, :name, {}, {class: "form-control"}

  .form-group
    = f.label :description
    = f.text_area :description, :class=>'form-control', placeholder: "Description"

  .actions.top_space
    = f.submit 'Save', :class=>"btn btn-success"
    - cancel_attr = { :class=>"btn btn-info"}
    - cancel_attr[:data] = { turbo_frame: '_top' } unless @framed
    = link_to 'Cancel', @after_cancel, cancel_attr

app/views/opportunities/_new_menu.html.haml
= turbo_frame_tag Opportunity.new do
  = link_to 'New Opportunity', new_opportunity_path, data: { turbo_frame: Opportunity.new }

app/views/opportunities/_opportunity.html.haml
= turbo_frame_tag opportunity do
  .opportunity.border.entry1
    .row
      .col-md-1
        - ava_pic = "#{opportunity.get_stage}_opportunity.jpg"
        = image_tag(ava_pic, :class=>"ava_pic", size: "150x150")
      .col-md-11
        %h2.index_show_button
          = link_to opportunity.title, opportunity_path(opportunity), data: { turbo_frame: '_top' }
        %p.about_text
          = opportunity.description

        .row
          .col-md-8
          .col-md-2
            = button_to 'Edit', edit_opportunity_path(opportunity), method: :get, class: 'btn btn-link'
          .col-md-2
            = button_to 'Delete', opportunity_path(opportunity), method: :delete, class: 'btn btn-link', form: { data: { turbo_confirm: "Are you sure you want to delete this?"} }

app/views/opportunities/after_edit.html.haml
= turbo_frame_tag 'new_opportunity' do
  = render partial: 'new_menu'

app/views/opportunities/create.turbo_stream.erb
<%= turbo_stream.prepend "opportunities", partial: 'opportunities/opportunity', locals: { opportunity: @opportunity } %>
<%= turbo_stream.update Opportunity.new, partial: 'new_menu' %>
<%= render_turbo_stream_flash_message %>

app/views/opportunities/destroy.turbo_stream.erb
<%= turbo_stream.remove @opportunity %>
<%= render_turbo_stream_flash_message %>

app/views/opportunities/edit.html.haml
- if @framed
  = turbo_frame_tag @opportunity do
    = render "edit_entry", opportunity: @opportunity
- else
  = render "edit_entry", opportunity: @opportunity

app/views/opportunities/index.html.haml
= turbo_stream_from 'opportunities'

%h1 Opportunities

= turbo_frame_tag "opportunities" do
  - @opportunities.ordered.each do |opportunity|
    = render opportunity

%p{:class=>'clearfix'}
  = paginate @opportunities

- content_for :sidebar do
  .container
    %h4 Add:
    = render partial: '/shared/new_menu'

app/views/opportunities/new.html.haml
= turbo_frame_tag Opportunity.new do
  = render 'form'

app/views/opportunities/show.html.haml
%h1
  = @opportunity.title

.alert.alert-success
  %h3
    = "Stage: #{ Opportunity::STAGES_LIST[@opportunity.stage] }"

.row
  .col-6
    %h3 Company:
    .expand_field
      = render partial: "companies/short_company", locals: {company: @opportunity.company}
  .col-6
    - if @opportunity.person
      %h3 Person:
      .expand_field
        = render partial: "people/short_person", locals: {person: @opportunity.person}

- content_for :sidebar do
  .ava_holder
    - ava_pic = "#{@opportunity.get_stage}_opportunity.jpg"
    = image_tag(ava_pic, :class=>"ava_pic", size: "150x150")

    .border.about_text_frame
      %p{:class=>"show_field"}
        %b Description:
        = @opportunity.description
  
  %p{:class=>"show_field"}
    %b Status:
    = Opportunity::STATUS_LIST[@opportunity.status]
  
  %p{:class=>"show_field"}
    %b Start:
    = @opportunity.start&.strftime('%T')

  %p{:class=>"show_field"}
    %b Finish:
    = @opportunity.finish&.strftime('%T')

  %p{:class=>"show_field"}
    %b Amount:
    = @opportunity.amount.to_s

  %p{:class=>"show_field"}
    %b Curator:
    = @opportunity.user.name


  = link_to 'Edit', edit_opportunity_path(@opportunity)
  \|
  = link_to 'Back to Opportunities List', opportunities_path

app/views/opportunities/update.turbo_stream.erb
<%= turbo_stream.replace @opportunity %>
<%= render_turbo_stream_flash_message %>